[build]
  publish = "."
  functions = "netlify/functions"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[functions]
  node_bundler = "esbuild"

[functions."parse-url"]
  timeout = 60

[env.production]
  [env.production.vars]
  MAPBOX_KEY = "pk.eyJ1IjoibWFyY3NvcmNpIiwiYSI6ImNtZ3F0Y3RtODBtbXYya3M0OHpwdHlheTMifQ.t2r9eVoc15UCAcQXKfBvIg"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false